import './components/loading'
import './components/theme'
import './components/language'
import './components/form'
import './components/banner'
import './components/btn-star-flow'
import './components/accordion'